"""APEX-7 — Layout package. Re-exports all public layout components."""

from dashboard.layout.classify import _classify_v2
from dashboard.layout.emotions import _EMOTIONS, _cycle, _emotion, _thinking
from dashboard.layout.helpers import (
    _action_chip,
    _analyst_body_children,
    _arb_card_children,
    _agent_eval_metrics,
    _body_style,
    _build_arb_card,
    _card_hdr_standard,
    _conf_bar_inline,
    _fmt_volume,
    _ind_cell,
    _load_agent_memory,
    _load_postmortem,
    _load_trades_db,
    _live_agent_eval_banner,
    _log_entry_card,
    _macro_bar,
    _macro_body_children,
    _make_sparkline_fig,
    _mini_stat,
    _pos_card,
    _risk_body_children,
    _section_label,
    _sent_bar,
    _sim_chip,
    _sparkline,
    _tech_body_children,
    _watchlist_row,
)
from dashboard.layout.main import setup_layout

setup_layout()

__all__ = [
    "_EMOTIONS",
    "_action_chip",
    "_analyst_body_children",
    "_arb_card_children",
    "_body_style",
    "_build_arb_card",
    "_card_hdr_standard",
    "_classify_v2",
    "_conf_bar_inline",
    "_cycle",
    "_emotion",
    "_fmt_volume",
    "_agent_eval_metrics",
    "_ind_cell",
    "_load_agent_memory",
    "_load_postmortem",
    "_load_trades_db",
    "_live_agent_eval_banner",
    "_log_entry_card",
    "_macro_bar",
    "_macro_body_children",
    "_make_sparkline_fig",
    "_mini_stat",
    "_pos_card",
    "_risk_body_children",
    "_section_label",
    "_sent_bar",
    "_sim_chip",
    "_sparkline",
    "_tech_body_children",
    "_thinking",
    "_watchlist_row",
    "setup_layout",
]
